spring:
  application:
    name: DOSW-Library
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dosw_library}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/dosw_library}
      auto-index-creation: true

app:
  persistence:
    mongo:
      enabled: ${MONGODB_ENABLED:false}
      write-mode: ${MONGODB_WRITE_MODE:SYNC}
      database: ${MONGODB_DATABASE:dosw_library}
server:
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}
    key-store: ${SERVER_SSL_KEY_STORE:}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
    key-alias: ${SERVER_SSL_KEY_ALIAS:}
  port: ${SERVER_PORT:8080}

security:
  cors:
    allowed-origin-patterns:
      - ${CORS_ALLOWED_ORIGIN_PATTERN:http://localhost:*}
  jwt:
    secret: 0123456789012345678901234567890101234567890123456789012345678901
    expiration-ms: 3600000
